name: Lint
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        architecture: x64
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - run: pip install .[dev]
    - run: isort --check-only ofdskit/ tests/ setup.py
    - run: black --check ofdskit/ tests/ setup.py
    - run: flake8 ofdskit/ tests/ setup.py
    - run: mypy --install-types --non-interactive -p ofdskit
